FizzBuzzDemo/MvcFizzBuzz.Web/Models/FizzBuzzDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MvcFizzBuzz.Web.Models
{
    public class FizzBuzzDto
    {
        public int InputNumber { get; set; }
        public string Output { get; set; }
        public string color { get; set; }
    }
}

FizzBuzzDemo/MvcFizzBuzz.Web/Models/FizzBuzzViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using PagedList;
using PagedList.Mvc;

namespace MvcFizzBuzz.Web.Models
{
    public class FizzBuzzViewModel
    {
        [Required(ErrorMessage = "Enter Number")]
        [Range(1, 1000, ErrorMessage = "Enter Number between 1 to 1000")]
        public int InputNumber { get; set; }
        public IPagedList<FizzBuzzDto> PagedLists { get; set; } 
    }
}

FizzBuzzDemo/MvcFizzBuzz.Web/Controllers/FizzBuzzController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcFizzBuzz.Web.Models;
using MvcFizzBuzz.Web.Repository;
using PagedList;
using PagedList.Mvc;

namespace MvcFizzBuzz.Web.Controllers
{
    /// <summary>
    /// Controller for viewing the list of Fizz Buzz Results
    /// </summary>
    
    public class FizzBuzzController : Controller
    {

        private IFuzzBuzzRepository fizzBuzzRepository;

        public FizzBuzzController(): this(new FuzzBuzzRepository())
        {

        }

        public FizzBuzzController(IFuzzBuzzRepository repository)
        {
            fizzBuzzRepository = repository;
         }


        /// <summary>
        /// Displays a list of Results by page Number
        /// </summary>
        /// <param name="page">The integer page Number</param>

        [HttpGet]
        public ActionResult Index(int? page)
        {
            FizzBuzzViewModel objmodel = null;
            if (TempData["FizzBuzzResult"] != null)
            {
                int pageNumber = (page ?? 1);
                int pageSize = 20;
                var result = (List<FizzBuzzDto>)TempData["FizzBuzzResult"];
                TempData.Keep("FizzBuzzResult");
                objmodel = new FizzBuzzViewModel();
                objmodel.PagedLists = result.ToPagedList(pageNumber, pageSize);
                return View(objmodel);
            }

           
            return View(objmodel);
        }

        /// <summary>
        /// Displays a list of All Results by entering inputNumber
        /// </summary>
        /// <param name="model">model is FizzBuzzViewModel for strongly typed Views </param>
        /// <param name="submitButton"> submitButton is a string to determine httpPost submit button name</param>

       
        [HttpPost]
        public ActionResult Index(FizzBuzzViewModel model)
        {           
            int pageNumber = 1;
            int pageSize = 20;
            FizzBuzzViewModel objmodel = null;

            var result = fizzBuzzRepository.FindFizzBuzz(model.InputNumber);
            objmodel = new FizzBuzzViewModel();
            objmodel.PagedLists = result.ToPagedList(pageNumber, pageSize);
            TempData["FizzBuzzResult"] = result;
            return View(objmodel);           
           
          }

                    
        }

    }

FizzBuzzDemo/MvcFizzBuzz.Web/Views/FizzBuzz/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@using MvcFizzBuzz.Web.Models;
@model MvcFizzBuzz.Web.Models.FizzBuzzViewModel

@{
    ViewBag.Title = "Index";
}

<h2> Calculate Fizz Buzz </h2>

<div style="font-family:Arial;">
 <p>
      @using (Html.BeginForm("Index", "FizzBuzz", FormMethod.Post))
      {
           @Html.ValidationSummary(true) 
          <div>
           @Html.TextBoxFor(m => m.InputNumber)  @Html.ValidationMessageFor(m => m.InputNumber) 
           </div>
           <br />
          <div>
          <input type="submit" value="Execute Number" name="submitButton" /> 
          </div>      
            
          
          <br />
          
          if(@Model != null)
          {
              foreach (FizzBuzzDto data in Model.PagedLists)
              {
                  <div>
	             
                 @if(@data.color =="Green")
                 {
                 <span style="color:Green; font-family:Verdana">&nbsp;
                    @Html.DisplayFor(m => data.Output)
                  </span>
                 }
                 else if (@data.color =="Red")
                 {
                  <span style="color:Red; font-family:Verdana">&nbsp;
                  @Html.DisplayFor(m => data.Output)
                  </span>
                 }
	              else if (@data.color =="Blue")
                  {
                  <span style="color:Blue; font-family:Verdana">&nbsp;
                  @Html.DisplayFor(m => data.Output)
                  </span>
                  }
                  else
                  {
                  <span>&nbsp;
                  @Html.DisplayFor(m => data.Output)
                   </span>
                  }
                 	
	             
              </div>
	              <br />
          
              }
          }
 
         
      <div>  
       @if (@Model != null)
       {

            @Html.PagedListPager(Model.PagedLists, page => Url.Action("Index", new { page, number=Model.InputNumber }), new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded, DisplayPageCountAndCurrentLocation = true, DisplayItemSliceAndTotal = true })
                
       }
      </div>

      }         

          
 
  </p>
      

  </div>